package net.bewis09.capyclient.util.color

import net.bewis09.capyclient.common.Color
import net.bewis09.capyclient.common.color
import net.bewis09.capyclient.game.translations.Translation

val colors = listOf(
    TranslatedColor(0xFF0000.color, "red", "Red"),
    TranslatedColor(0x00FF00.color, "green", "Green"),
    TranslatedColor(0x0000FF.color, "blue", "Blue"),
    TranslatedColor(0xFFFF00.color, "yellow", "Yellow"),
    TranslatedColor(0x00FFFF.color, "cyan", "Cyan"),
    TranslatedColor(0xFF00FF.color, "magenta", "Magenta"),
    TranslatedColor(0xFFFFFF.color, "white", "White"),
    TranslatedColor(0x000000.color, "black", "Black"),
    TranslatedColor(0x808080.color, "gray", "Gray"),
    TranslatedColor(0x404040.color, "dark_gray", "Dark Gray"),
    TranslatedColor(0xC0C0C0.color, "light_gray", "Light Gray"),
    TranslatedColor(0xFFA500.color, "orange", "Orange"),
    TranslatedColor(0xFFC0CB.color, "pink", "Pink"),
    TranslatedColor(0x800080.color, "purple", "Purple"),
    TranslatedColor(0xA52A2A.color, "brown", "Brown"),
    TranslatedColor(0x00FF00.color, "lime", "Lime"),
    TranslatedColor(0x008080.color, "teal", "Teal"),
    TranslatedColor(0x000080.color, "navy", "Navy"),
    TranslatedColor(0x808000.color, "olive", "Olive"),
    TranslatedColor(0x800000.color, "maroon", "Maroon"),
    TranslatedColor(0xFFD700.color, "gold", "Gold"),
    TranslatedColor(0xC0C0C0.color, "silver", "Silver"),
    TranslatedColor(0x4B0082.color, "indigo", "Indigo"),
    TranslatedColor(0xEE82EE.color, "violet", "Violet"),
    TranslatedColor(0xFF7F50.color, "coral", "Coral"),
    TranslatedColor(0xFA8072.color, "salmon", "Salmon"),
    TranslatedColor(0xF0E68C.color, "khaki", "Khaki"),
    TranslatedColor(0xDDA0DD.color, "plum", "Plum"),
    TranslatedColor(0xDA70D6.color, "orchid", "Orchid"),
    TranslatedColor(0x40E0D0.color, "turquoise", "Turquoise"),
    TranslatedColor(0xDC143C.color, "crimson", "Crimson"),
    TranslatedColor(0xA0522D.color, "sienna", "Sienna"),
    TranslatedColor(0xD2691E.color, "chocolate", "Chocolate"),
    TranslatedColor(0xD2B48C.color, "tan", "Tan"),
    TranslatedColor(0xFFDAB9.color, "peach", "Peach"),
    TranslatedColor(0xE6E6FA.color, "lavender", "Lavender"),
    TranslatedColor(0x98FF98.color, "mint", "Mint"),
    TranslatedColor(0x87CEEB.color, "sky_blue", "Sky Blue"),
    TranslatedColor(0x00FFFF.color, "aqua", "Aqua"),
    TranslatedColor(0x228B22.color, "forest_green", "Forest Green"),
    TranslatedColor(0x4169E1.color, "royal_blue", "Royal Blue"),
    TranslatedColor(0xFF1493.color, "deep_pink", "Deep Pink"),
    TranslatedColor(0xB22222.color, "firebrick", "Firebrick"),
    TranslatedColor(0x4682B4.color, "steel_blue", "Steel Blue"),
    TranslatedColor(0x006400.color, "dark_green", "Dark Green"),
    TranslatedColor(0x8B0000.color, "dark_red", "Dark Red"),
    TranslatedColor(0x00008B.color, "dark_blue", "Dark Blue"),
    TranslatedColor(0xFF69B4.color, "hot_pink", "Hot Pink"),
    TranslatedColor(0x32CD32.color, "lime_green", "Lime Green"),
    TranslatedColor(0xFF4500.color, "orange_red", "Orange Red"),
    TranslatedColor(0x2E8B57.color, "sea_green", "Sea Green"),
    TranslatedColor(0x708090.color, "slate_gray", "Slate Gray"),
    TranslatedColor(0x9370DB.color, "medium_purple", "Medium Purple"),
    TranslatedColor(0xFF8C00.color, "dark_orange", "Dark Orange"),
    TranslatedColor(0xADD8E6.color, "light_blue", "Light Blue"),
    TranslatedColor(0x90EE90.color, "light_green", "Light Green"),
    TranslatedColor(0xFFB6C1.color, "light_pink", "Light Pink"),
    TranslatedColor(0xF5DEB3.color, "wheat", "Wheat"),
)

class TranslatedColor(val color: Color, id: String, text: String) {
    val translation = Translation("color.$id", text)
}